service: verifier-serverless
app: verifier-app
org: spott

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  profile: spott
  apiName: verifier-api
  apiKeys:
    - x9gflvez3g
  apiGateway:
    apiKeySourceType: HEADER

functions:
  server:
    handler: lib/server/lambda-handler.server
    environment:
      NODE_ENV: production
    events:
      - http:
          path: rfc/verify
          method: post
          cors: true
          private: true
